#!/usr/bin/env bash

# Detect operating platform and install SBCL
if [ $(command -v xbps-query) ]; then
    # Void Linux
    sudo xbps-install -Syu sbcl
elif [ $(command -v pacman) ]; then
    # Arch Linux
    sudo pacman -Sy sbcl
elif [ $(command -v dnf) ]; then
    # Fedora Linux
    sudo dnf install -y sbcl
elif [ $(command -v apt) ]; then
    # Debian Linux
    sudo apt install -y sbcl
fi # TODO: Add support for more operating systems

# Fetch and bootstrap Quicklisp
curl https://beta.quicklisp.org/quicklisp.lisp -o /tmp/quicklisp.lisp
sbcl --script ./bootstrap-quicklisp.lisp
